Firebase auth backend
googleinterns/step204-2020 pull request #96
Opened 2020-08-06 08:46 UTC by SibingWu

Set up the `createSessionCookie`, `verifySessionCookie`, and `clearSessionCookie` at the backend

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            String idToken = getIDToken(request);
nit: maybe call this function parseIDToken? just to be consistent with the other servlets

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            long expiresIn = TimeUnit.DAYS.toMillis(/* duration= */5);
nit: extract the duration out into a constant?

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            NewCookie cookie = new NewCookie(/* name= */ "session", sessionCookie);
nit: constant for "session" name?

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +        final int maxAge = 0;
what is maxAge?

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +                .setDatabaseUrl("https://com-walk-in-interview.firebaseio.com/")
maybe extract these out into constants as well? DATABASE_URL and PROJECT_ID

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +        String idToken = request.getParameter(ID_TOKEN_PARAM).trim();
maybe you can use something like: 
`        String jobIdStr = ServletUtils.getStringParameter(request, JOB_ID_FIELD, /* defaultValue= */ "");
`

2020-08-06 09:39 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +        String uid = decodedToken.getUid();
could this be null or empty?

2020-08-06 12:38 UTC, riya-n approved these changes

2020-08-06 12:38 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +    private static final int SESSION_COOKIE_DURATION_DAY = 5;
nit: SESSION_COOKIE_DURATION_DAYS

2020-08-06 12:38 UTC, riya-n commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            FirebaseToken decodedToken = FirebaseAuth.getInstance().verifySessionCookie(sessionCookie, checkRevoked);
nit: `FirebaseAuth.getInstance().verifySessionCookie(sessionCookie, /* checkRevoked= */ true);`

2020-08-07 02:30 UTC, yohanlaunay requested changes

2020-08-07 02:30 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            // Sets session expiration to 5 days
nit, you should remove the "5 days" from your comment., it's defined by your constant. You can just say "set the expiration".

2020-08-07 02:30 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            return Response.status(Response.Status.UNAUTHORIZED).entity("Failed to create a session cookie").build();
please log the exception

2020-08-07 02:30 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +            // Session cookie is unavailable, invalid or revoked. Force user to login.
please log the exception

2020-08-07 02:38 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +public final class FirebaseAuthSessionCookieUtil {
please rename to FirebaseAuthSessionCookieServlet

2020-08-07 02:56 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/FirebaseAuthSessionCookieUtil.java
> +        final int maxAge = 0;
you need to actually clear the firebase session here:
- extract the sessionToken
- clear it with firebase
- return an expired cookie

2020-08-07 11:06 UTC, yohanlaunay approved these changes

2020-08-07 11:06 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/CreateSessionCookieServlet.java
> +    private static final String DATABASE_URL = "https://com-walk-in-interview.firebaseio.com/";
`TODO(issue/) move to config file`

2020-08-07 11:06 UTC, yohanlaunay commented on walk-in-interview/src/main/java/com/google/account/CreateSessionCookieServlet.java
> +    private void initAdminSDK() throws IOException {
nit: ideally this should be moved to your `FirebaseAuthUtils#initAdminSdk(databaseUrl, projectId, projectName);`

2020-08-07 11:26 UTC, merged